language: php

sudo: false

php:
  - 7.4

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

script:
  - php bin/benchmark --iteration=3 --rows=10000 --cells=5 --driver=Spout
  - php bin/benchmark --iteration=3 --rows=10000 --cells=5 --driver=SpreadsheetExcelWriter
  - php bin/benchmark --iteration=3 --rows=10000 --cells=5 --driver=Phpspreadsheet
  - php bin/benchmark --iteration=3 --rows=20000 --cells=5 --driver=Spout
  - php bin/benchmark --iteration=3 --rows=20000 --cells=5 --driver=SpreadsheetExcelWriter
  - php bin/benchmark --iteration=3 --rows=20000 --cells=5 --driver=Phpspreadsheet
  - php bin/benchmark --iteration=3 --rows=30000 --cells=5 --driver=Spout
  - php bin/benchmark --iteration=3 --rows=30000 --cells=5 --driver=SpreadsheetExcelWriter
  - php bin/benchmark --iteration=3 --rows=30000 --cells=5 --driver=Phpspreadsheet
  - php bin/benchmark --iteration=3 --rows=40000 --cells=5 --driver=Spout
  - php bin/benchmark --iteration=3 --rows=40000 --cells=5 --driver=SpreadsheetExcelWriter
  - php bin/benchmark --iteration=3 --rows=40000 --cells=5 --driver=Phpspreadsheet
  - php bin/benchmark --iteration=3 --rows=50000 --cells=5 --driver=Spout
  - php bin/benchmark --iteration=3 --rows=50000 --cells=5 --driver=SpreadsheetExcelWriter
  - php bin/benchmark --iteration=3 --rows=50000 --cells=5 --driver=Phpspreadsheet
  - php bin/benchmark --iteration=3 --rows=65534 --cells=5 --driver=Spout
  - php bin/benchmark --iteration=3 --rows=65534 --cells=5 --driver=SpreadsheetExcelWriter
  - php bin/benchmark --iteration=3 --rows=65534 --cells=5 --driver=Phpspreadsheet
